# ==================================
# IDENTIFICACIÓN DE LA APP
# ==================================
spring.application.name=gestioneventos
# ==================================
# SERVIDOR (ACCESO EN RED LOCAL)
# ==================================
server.address=0.0.0.0
server.port=8080

# ==================================
# DATOS DE CONEXIÓN POSTGRESQL (NEON)
# ==================================
spring.datasource.url=jdbc:postgresql://ep-holy-cake-a44vpd11.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${GESTION_EVENTOS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# POOL DE CONEXIONES (IMPORTANTE)
# ==================================
# Validar conexión antes de usarla
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000

# Tiempo máximo que una conexión puede estar inactiva (5 min)
spring.datasource.hikari.idle-timeout=300000

# Tiempo máximo de vida de una conexión (10 min)
spring.datasource.hikari.max-lifetime=600000

# Neon tarda en despertar, dale más tiempo
spring.datasource.hikari.connection-timeout=30000

# Pool mínimo/máximo
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
# ==================================
# CONFIGURACIÓN JPA / HIBERNATE
# ==================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==================================
# LOGS
# ==================================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
