# ==================================
# IDENTIFICACIÓN DE LA APP
# ==================================
spring.application.name=gestioneventos
# ==================================
# SERVIDOR (ACCESO EN RED LOCAL)
# ==================================
server.address=0.0.0.0
server.port=8080

# ==================================
# DATOS DE CONEXIÓN POSTGRESQL (NEON)
# ==================================
spring.datasource.url=jdbc:postgresql://ep-holy-cake-a44vpd11.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${GESTION_EVENTOS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# POOL DE CONEXIONES (IMPORTANTE)
# ==================================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# ==================================
# CONFIGURACIÓN JPA / HIBERNATE
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==================================
# LOGS
# ==================================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
